export const products = [
    {
        id: 1,
        name: "Classic White Tee",
        description: "A timeless essential for any wardrobe",
        price: 19.99,
        image: "https://picsum.photos/id/10/200",
        category: "Mens",
    },
    {
        id: 2,
        name: "Floral Sundress",
        description: "Lightweight and breezy for summer days",
        price: 39.99,
        image: "https://picsum.photos/id/11/200",
        category: "Womens",
    },
    {
        id: 3,
        name: "Slim Fit Chinos",
        description: "Versatile and comfortable chino pants",
        price: 29.99,
        image: "https://picsum.photos/id/20/200",
        category: "Mens",
    },
    {
        id: 4,
        name: "Lace Blouse",
        description: "Elegant and feminine blouse with lace details",
        price: 24.99,
        image: "https://picsum.photos/id/13/200",
        category: "Womens",
    },
    {
        id: 5,
        name: "Denim Jacket",
        description: "Classic denim jacket for any occasion",
        price: 49.99,
        image: "https://picsum.photos/id/40/200",
        category: "Mens",
    },
    {
        id: 6,
        name: "Maxi Skirt",
        description: "Flowing and comfortable maxi skirt",
        price: 34.99,
        image: "https://picsum.photos/id/51/200",
        category: "Womens",
    },
    {
        id: 7,
        name: "Striped Polo",
        description: "Classic polo shirt with a modern twist",
        price: 24.99,
        image: "https://picsum.photos/id/17/200",
        category: "Mens",
    },
    {
        id: 8,
        name: "Pleated Midi Dress",
        description: "Elegant and sophisticated midi dress",
        price: 59.99,
        image: "https://picsum.photos/id/63/200",
        category: "Womens",
    },
];